---
- hosts: dcos_cluster
  remote_user: root

  tasks:
    - name: download do-agent
      get_url: 
        url: https://agent.digitalocean.com/install.sh
        dest: /tmp/dom_install.sh
        mode: 0755
    
    - name: install do-agent
      shell: /tmp/dom_install.sh

    - name: mount /tmp in exec mode
      command: mount -t tmpfs -o remount,exec /tmp

    - name: setup epel-repo and update
      yum:
        name: epel-release
        state: latest
    
    - name: add docker registry
      yum_repository:
        name: docker
        description: Docker Yum repo
        file: docker.repo
        baseurl: "https://yum.dockerproject.org/repo/main/centos/{{ ansible_distribution_major_version }}"
        gpgcheck: yes
        gpgkey: https://yum.dockerproject.org/gpg

    - name: yum update
      yum:
        name: '*'
        state: latest

    - name: install docker
      yum:
        name: "{{ item }}"
        state: present
      with_items: 
        - docker-engine-1.13.1
        - docker-engine-selinux-1.13.1
    
    - name: create docker.service.d
      file: /etc/systemd/system/docker.service.d
      state: directory
      mode: 0755

    - name: add docker specific conf
      copy:
        src: "files/{{ item }}"
        dest: "/etc/systemd/system/docker.service.d/{{ item }}"
        mode: 0644
        force: yes
      with_items:
        - execstart.conf
        - override.conf
    
    - name: enable/start docker
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: disable firewalld/dnsmasq
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items:
        - firewalld
        - dnsmasq

- hosts: boot_host
  remote_user: root
  
  tasks:
    - name: download dc/os installer
      get_url:
        url: https://downloads.dcos.io/dcos/stable/dcos_generate_config.sh
        dest: /tmp/dcos_generate_config.sh
        mode: 0755